### ISSUE TITLE
Pooling

### ISSUE THREAD

**Issue by moll** [uber/multitransport-jsonrpc#57]
Hey!

How do you guys go about pooling? I'm saturating a single Node RPC server process with some computations and would like to transparently have clients use different server workers for requests. It's easy to set up a clustered RPC server, but as client connections are long running, they won't be getting the benefit without client-side modifications. That implies some sort of a pool and per-request round batmanning.

What do others do?

**Comment by moll** [comment]
I've since written a light-weight replacement JSON-RPC library that presents a DuplexStream interface for piping plain TCP streams to and from (with an intermediary component doing message framing). With a small stream router in between to send those messages to child workers, it's works marvelously. Hope to open-source it this year, too. :-)

**Comment by sh1mmer** [comment]
@dfellis have you considered lb_pool?

cc @mranney

**Comment by mranney** [comment]
Another thing you might want to check out is: https://github.com/uber/tchannel
