### ISSUE TITLE
Use tcp socket inside method

### ISSUE THREAD

**Issue by Lughino** [uber/multitransport-jsonrpc#74]
Is there a way to use the socket within methods?

example:
a user "A" calls a method that sends a message, users connected to "A" should receive the message and if they are connected through socket is also necessary to have the socket.

Is there a way to access it?

**Comment by dfellis** [comment]
I'm not entirely sure what you're asking for? You want access to the raw socket that's being used by the RPC call?

If that's the case, the answer is basically no for the server: [The HTTP Server never exposes the request or response objects](https://github.com/uber/multitransport-jsonrpc/blob/master/lib/transports/server/http.js#L20-L42) and [neither does the TCP server](https://github.com/uber/multitransport-jsonrpc/blob/master/lib/transports/server/tcp.js#L27-L43).

If you mean from the client perspective you can inspect that [only from the TCP client](https://github.com/uber/multitransport-jsonrpc/blob/master/lib/transports/client/tcp.js#L29) with the `this.con` property.

**Comment by Lughino** [comment]
I understand that with regard to the server the raw socket http has no use, but the raw socket tcp, always server side, would use if it were available.

Let's take a case like this:
real-time application based tcp ..
- Two users (A and B) open a socket to the server;
- User "A" sends a message to user "B"
- The server, if it can access the socket, sends the message through the socket opened by the user "B"

The last point I can not run it because I can not access the object with the open socket, [see this line of code](https://github.com/uber/multitransport-jsonrpc/blob/master/lib/transports/server/tcp.js#L28).
We can find a way to access that object?

I hope I explained myself better, I apologize for my English.

**Comment by dfellis** [comment]
Yes. You want a message-passing server, but this is code for a remote procedure call (rpc) server and client.

Even if you had access to that socket, you would still need to significantly refactor the client code as it assumes that the server *never* initiates an action, and wouldn't know what to do with the forwarded RPC request.

This is not the library you need.
